version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/dov/backend
    depends_on:
      - mysql

  mysql:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: DOV
      ENV MYSQL_USER: DOV_ADMIN
      ENV MYSQL_PASSWORD: 1q2w3e4r
    volumes:
      - "./init/:/docker-entrypoint-initdb.d/"
